### PR TITLE
Parametrization

### PR DESCRIPTION
**Pull request by AlexisBRENON**
Add more variables and automatic generation.

### CODE REVIEW

**Comment by afonsopacifer** [comment]
Awesome!
I'm reviewing  :)

**Comment by afonsopacifer** [comment]
Sorry for the delay ;)

@AlexisBRENON Thanks, great job!!

**Comment by AlexisBRENON** [comment]
No problem. You're welcome.

**Comment by dimensi** [comment]
@AlexisBRENON
For what it's done?

```
margin-left -1 * flx-padding
margin-right -1 * flx-padding
```

It's broke...

**Comment by AlexisBRENON** [comment]
Sorry @edDimensi I don't understand what you mean...
Can you explain more ?

**Comment by dimensi** [comment]
@AlexisBRENON 
Why this site code?

```
margin-left -1 * flx-padding
margin-right -1 * flx-padding
```

Because of this section of code in my blocks `@extend $row` no longer are centralized.

**Comment by dimensi** [comment]
@AlexisBRENON 
I do not know English, and unfortunately I can not explain more precisely what I am not happy. I apologize for this. But I can not understand what does it do? What does it do? If you do so, then the block will simply break down and not work.
http://codepen.io/dimensi/pen/RRWOwG

**Comment by AlexisBRENON** [comment]
Hi @edDimensi 

Well, actually this kind of trick is used to remove left margin on the first column and right margin on the last one. This way, your columns are aligned with other blocks of your site that don't use columns.
This is inspired by the Bootstrap work. It's also useful when you nest columns to avoid too many margin/padding on the first and last column.

Perhaps this is not the better way to fix these issues.

For the moment, the easiest way for you to restore the default behavior is to override this value with:

``` stylus
.block
  margin-right auto
  margin-left auto
```

I'll look forward is there a way to achieve what I explain without breaking the centering feature.

**Comment by AlexisBRENON** [comment]
Hi @edDimensi 

Look at this [codepen](http://codepen.io/AlexisBRENON/pen/EyWvzb), it presents different uses of columns. It appears that your bug can be caused by two CSS attributes, margins (as seen previously) but also the max-width of a row. 

I don't know why @afonsopacifer restrict the width of the row to an arbitrary 1200px... Maybe he can explain us here.

Then, as you can see on the codepen, responsive-width and negative margins have their pros and cons (negative margin is not straightforward to understand). Maybe @afonsopacifer must decide what is a feature of the framework, what is a side effect which must be marked as deprecated or something like so.

Kind regards,
Alexis

**Pull request merged**
